from __future__ import annotations

import collections
import re
import shlex
from pathlib import Path
from typing import TYPE_CHECKING, Final

from ... import Command
from ...batoceraPaths import KNULLI_SHARE_DIR, CONFIGS, LOGS, mkdir_if_not_exists
from ...controller import generate_sdl_game_controller_config
from ..Generator import Generator

if TYPE_CHECKING:
    from ...types import HotkeysContext

_CONFIG_DIR: Final = CONFIGS / "gzdoom"
_INI_FILE: Final = _CONFIG_DIR / "gzdoom.ini"
_SCRIPT_FILE: Final = _CONFIG_DIR / "gzdoom.cfg"
_FM_BANKS_DIR: Final = _CONFIG_DIR / "fm_banks"
_SOUND_FONTS_DIR: Final = _CONFIG_DIR / "soundfonts"

class IniFileEditor:

    def __init__(self, path: Path):
        self.path = path
        self.sections: dict[str, list[str]] = collections.defaultdict(list)
        if self.path.exists():
            self._parse()

    def _parse(self) -> None:
        current_section = ""
        with self.path.open("r", encoding="utf-8") as f:
            for line in f:
                stripped_line = line.strip()
                if stripped_line.startswith("[") and stripped_line.endswith("]"):
                    current_section = stripped_line
                    # Ensure the section key exists even if it's empty
                    if current_section not in self.sections:
                        self.sections[current_section] = []
                elif current_section and stripped_line:
                    self.sections[current_section].append(line)

    def ensure_section_exists(self, section_name: str) -> None:
        if section_name not in self.sections:
            self.sections[section_name] = []

    def set_value(self, section: str, key: str, value: str) -> None:
        self.ensure_section_exists(section)
        full_line = f"{key}={value}\n"
        # Find and replace existing key
        for i, line in enumerate(self.sections[section]):
            if line.strip().startswith(f"{key}="):
                self.sections[section][i] = full_line
                return
        # Or add if it doesn't exist
        self.sections[section].append(full_line)

    def set_value_if_missing(self, section: str, key: str, value: str) -> None:
        self.ensure_section_exists(section)
        # Check if the key already exists
        for line in self.sections[section]:
            if line.strip().startswith(f"{key}="):
                return  # Key found, so we do nothing
        # Key was not found, add it
        self.sections[section].append(f"{key}={value}\n")

    def add_line_if_missing(self, section: str, line_to_add: str) -> None:
        self.ensure_section_exists(section)
        # Ensure the line ends with a newline
        line_with_newline = line_to_add.strip() + "\n"
        if line_with_newline not in self.sections[section]:
            self.sections[section].append(line_with_newline)

    def write(self) -> None:
        with self.path.open("w", encoding="utf-8") as f:
            for section_name, lines in self.sections.items():
                f.write(f"{section_name}\n")
                for line in lines:
                    f.write(line)
                f.write("\n")

class GZDoomGenerator(Generator):

    def getHotkeysContext(self) -> HotkeysContext:
        return {
            "name": "gzdoom",
            "keys": { "exit": ["KEY_LEFTALT", "KEY_F4"], "save_store": "KEY_F6", "restore_store": "KEY_F9" }
        }

    def _determine_api_config(self, system) -> str:
        gzdoom_api = system.config.get("gz_api", "0")
        arch_path = KNULLI_SHARE_DIR / "knulli.arch"

        # Default to GLES on non-x86_64 architectures if API is auto ("0")
        if gzdoom_api == "0" and arch_path.exists():
            arch = arch_path.read_text().strip()
            if arch != "x86_64":
                gzdoom_api = "3"

        if gzdoom_api == "3":
            # OpenGL ES settings for performance
            return (
                "gl_es 1\n"
                "vid_preferbackend 3\n"
                "gles_use_mapped_buffer true\n"
            )
        return f"vid_preferbackend {gzdoom_api}\n"

    def _create_script_file(self, system, api_config: str) -> None:
        content = (
            "# This file is automatically generated by gzdoomGenerator.py\n"
            f"logfile \"{LOGS / 'gzdoom.log'}\"\n"
            f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
            f"{api_config}"
            "echo BATOCERA\n"
        )
        _SCRIPT_FILE.write_text(content, encoding="utf-8")

    def _update_ini_file(self, system, rom: Path, playersControllers) -> None:
        ini = IniFileEditor(_INI_FILE)

        DEFAULT_BINDINGS = {
            "1": "slot 1", "2": "slot 2", "3": "slot 3", "4": "slot 4", "5": "slot 5",
            "6": "slot 6", "7": "slot 7", "8": "slot 8", "9": "slot 9", "0": "slot 0",
            "W": "+forward", "S": "+back", "A": "+moveleft", "D": "+moveright", "E": "+use",
            "T": "messagemode", "LeftBracket": "invprev", "RightBracket": "invnext",
            "Enter": "invuse", "Shift": "+speed", "X": "crouch", "Space": "+jump",
            "Tab": "togglemap", "`": "toggleconsole", "\\": "+showscores", "CapsLock": "toggle cl_run",
            "F1": "menu_help", "F2": "menu_save", "F3": "menu_load", "F4": "menu_options",
            "F5": "menu_display", "F6": "quicksave", "F7": "menu_endgame", "F8": "togglemessages",
            "F9": "quickload", "F10": "menu_quit", "F11": "bumpgamma", "F12": "spynext",
            "SysRq": "screenshot", "Pause": "pause", "Home": "land", "PgUp": "+moveup",
            "End": "centerview", "PgDn": "+lookup", "Ins": "+movedown", "Del": "+lookdown",
            "Mouse1": "+attack", "Mouse2": "+altattack", "MWheelUp": "weapprev",
            "MWheelDown": "weapnext", "MWheelRight": "invnext", "MWheelLeft": "invprev",
        }

        DEFAULT_AUTOMAP_BINDINGS = {
            "0": "am_gobig", "=": "+am_zoomin", "-": "+am_zoomout",
            "P": "am_toggletexture", "F": "am_togglefollow", "G": "am_togglegrid",
            "C": "am_clearmarks", "M": "am_setmark",
            "KP-": "+am_zoomout", "KP+": "+am_zoomin",
            "UpArrow": "+am_panup", "LeftArrow": "+am_panleft",
            "RightArrow": "+am_panright", "DownArrow": "+am_pandown",
            "MWheelUp": "am_zoom 1.2", "MWheelDown": "am_zoom -1.2",
        }

        GZDOOM_JOY_BINDINGS = {
            "b": "+jump",
            "a": "+use",
            "y": "reload",
            "x": "turn180",
            "pageup": "weapprev",
            "pagedown": "weapnext",
            "l2": "+altattack",
            "r2": "+attack",
            "l3": "toggle cl_run",
            "r3": "crouch",
            "start": "menu_main",
            "select": "togglemap",
        }

        # Get look sensitivity settings
        set_gz_look_sensitivity_h = system.config.get("gz_look_sensitivity_h", "1.00")
        set_gz_look_sensitivity_v = system.config.get("gz_look_sensitivity_v", "0.25")

        if system.getOptBoolean("gz_look_invert_y"):
            set_gz_look_sensitivity_v = f"-{set_gz_look_sensitivity_v}"

        first_pad = next(iter(playersControllers.values()), None)
        input_names = {
            inp.name
            for inp in first_pad.inputs.values()
        } if first_pad is not None else set()

        has_left_stick = {
            "joystick1left",
            "joystick1up",
        }.issubset(input_names)

        has_right_stick = {
            "joystick2left",
            "joystick2up",
        }.issubset(input_names)

        has_dual_stick = has_left_stick and has_right_stick

        GZDOOM_AXIS_MAP_DUAL_STICK = {
            "joystick1left": {"map": 3, "scale": "1"},  # strafe
            "joystick1up":   {"map": 2, "scale": "1"},  # forward/back
            "joystick2left": {"map": 0, "scale": set_gz_look_sensitivity_h},  # turn
            "joystick2up":   {"map": 1, "scale": set_gz_look_sensitivity_v},  # look
        }

        GZDOOM_AXIS_MAP_SINGLE_STICK = {
            "joystick1left": {"map": 0, "scale": set_gz_look_sensitivity_h},  # turn
            "joystick1up":   {"map": 2, "scale": "1"},  # forward/back
        }

        GZDOOM_AXIS_MAP = {}

        if has_dual_stick:
            GZDOOM_AXIS_MAP = GZDOOM_AXIS_MAP_DUAL_STICK
        elif has_left_stick:
            GZDOOM_AXIS_MAP = GZDOOM_AXIS_MAP_SINGLE_STICK

        GZDOOM_DPAD_BINDINGS = {
            "up": {
                "suffix": "Up",
                "doom": "centerview",
                "automap": "+am_panup",
            },
            "down": {
                "suffix": "Down",
                "doom": "invuse",
                "automap": "+am_pandown",
            },
            "left": {
                "suffix": "Left",
                "doom": "invprev",
                "automap": "+am_panleft",
            },
            "right": {
                "suffix": "Right",
                "doom": "invnext",
                "automap": "+am_panright",
            },
        }

        GZDOOM_DPAD_BINDINGS_MOVEMENT = {
            "up": {
                "suffix": "Up",
                "doom": "+forward",
                "automap": "+am_panup",
            },
            "down": {
                "suffix": "Down",
                "doom": "+back",
                "automap": "+am_pandown",
            },
            "left": {
                "suffix": "Left",
                "doom": "+left",
                "automap": "+am_panleft",
            },
            "right": {
                "suffix": "Right",
                "doom": "+right",
                "automap": "+am_panright",
            },
        }

        if not has_left_stick:
            GZDOOM_DPAD_BINDINGS = GZDOOM_DPAD_BINDINGS_MOVEMENT

        GZDOOM_JOY_AUTOMAP_BINDINGS = {
            "a": "am_setmark",
            "b": "am_clearmarks",
            "x": "am_togglefollow",
            "y": "am_togglegrid",
            "pageup": "+am_zoomout",
            "pagedown": "+am_zoomin",
        }

        # Add ROM path to search directories
        rom_path_line = f"Path={rom.parent}"
        ini.add_line_if_missing("[IWADSearch.Directories]", rom_path_line)
        ini.add_line_if_missing("[FileSearch.Directories]", rom_path_line)

        # Add sound and music paths (system paths first, for precedence)
        sound_paths = [
            "Path=/usr/share/gzdoom/soundfonts",
            "Path=/usr/share/gzdoom/fm_banks",
            f"Path={_SOUND_FONTS_DIR}",
            f"Path={_FM_BANKS_DIR}",
        ]
        for path_line in sound_paths:
            ini.add_line_if_missing("[SoundfontSearch.Directories]", path_line)

        # ES Settings
        set_gz_vsync = system.config.get("gz_vsync", "false")
        set_gz_maxfps = system.config.get("gz_maxfps", "60")
        set_gz_capfps = system.config.get("gz_capfps", "true")
        set_gz_ui_scale = system.config.get("gz_ui_scale", "2")

        ini.set_value("[GlobalSettings]", "vid_vsync", set_gz_vsync)
        ini.set_value("[GlobalSettings]", "vid_maxfps", set_gz_maxfps)
        ini.set_value("[GlobalSettings]", "cl_capfps", set_gz_capfps)
        ini.set_value("[Doom.ConsoleVariables]", "uiscale", set_gz_ui_scale)
        ini.set_value("[Doom.ConsoleVariables]", "screenblocks", "11")
        ini.set_value("[Doom.ConsoleVariables]", "saved_screenblocks", "11")
        # Set joystick option
        ini.set_value("[GlobalSettings]", "use_joystick", "true")

        # Default all axes to disabled. Valid axis are set below.
        for axis in range(0, 6):
            ini.set_value("[Joy:JS:0]", f"Axis{axis}deadzone", "1.0")
            ini.set_value("[Joy:JS:0]", f"Axis{axis}scale", "1")
            ini.set_value("[Joy:JS:0]", f"Axis{axis}map", "-1")

        # 1. Apply default bindings if they are missing (first start)
        for key, value in DEFAULT_BINDINGS.items():
            ini.set_value_if_missing("[Doom.Bindings]", key, value)
        for key, value in DEFAULT_AUTOMAP_BINDINGS.items():
            ini.set_value_if_missing("[Doom.AutomapBindings]", key, value)

        # 2. Set/Overwrite dynamic controller bindings
        # First, clear any existing Joy#, Axis#, DPad/POV, etc bindings to prevent conflicts from previous runs.
        controller_binding_re = re.compile(
            r"(Joy\d+|Axis\d+(Plus|Minus)?|DPad\w+|POV\d+\w+|Pad_\w+|[LR](Thumb|Shoulder|Trigger))\s*="
        )

        ini.sections["[Doom.Bindings]"] = [
            line for line in ini.sections["[Doom.Bindings]"]
            if not controller_binding_re.match(line.strip())
        ]

        ini.sections["[Doom.AutomapBindings]"] = [
            line for line in ini.sections["[Doom.AutomapBindings]"]
            if not controller_binding_re.match(line.strip())
        ]

        # GZDoom's internal joystick handler for controllers is not dynamic
        # We need to set the Joy values for controllers i.e. Joy1=+use Joy4=+jump etc
        for n, pad in enumerate(playersControllers.values()):
            if n == 0:
                ini.set_value(f"[Joy:JS:{n}]", "Enabled", "1")

                for inp in pad.inputs.values():
                    if inp.type == "button":
                        joynum = int(inp.id) + 1

                        if inp.name in GZDOOM_JOY_BINDINGS:
                            ini.set_value(
                                "[Doom.Bindings]",
                                f"Joy{joynum}",
                                GZDOOM_JOY_BINDINGS[inp.name],
                            )

                        if inp.name in GZDOOM_JOY_AUTOMAP_BINDINGS:
                            ini.set_value(
                                "[Doom.AutomapBindings]",
                                f"Joy{joynum}",
                                GZDOOM_JOY_AUTOMAP_BINDINGS[inp.name],
                            )

                        # Some controllers dpad are buttons instead of hat
                        if inp.name in GZDOOM_DPAD_BINDINGS:
                            binding = GZDOOM_DPAD_BINDINGS[inp.name]

                            ini.set_value(
                                "[Doom.Bindings]",
                                f"Joy{joynum}",
                                binding["doom"],
                            )
                            ini.set_value(
                                "[Doom.AutomapBindings]",
                                f"Joy{joynum}",
                                binding["automap"],
                            )

                    elif inp.type == "hat" and inp.name in GZDOOM_DPAD_BINDINGS:
                        binding = GZDOOM_DPAD_BINDINGS[inp.name]
                        hatnum = int(inp.id) + 1
                        suffix = binding["suffix"]

                        ini.set_value(
                            "[Doom.Bindings]",
                            f"POV{hatnum}{suffix}",
                            binding["doom"],
                        )
                        ini.set_value(
                            "[Doom.AutomapBindings]",
                            f"POV{hatnum}{suffix}",
                            binding["automap"],
                        )

                        if hatnum == 1:
                            ini.set_value(
                                "[Doom.Bindings]",
                                f"DPad{suffix}",
                                binding["doom"],
                            )
                            ini.set_value(
                                "[Doom.AutomapBindings]",
                                f"DPad{suffix}",
                                binding["automap"],
                            )

                    elif inp.type == "axis" and inp.name in GZDOOM_AXIS_MAP:
                        mapping = GZDOOM_AXIS_MAP[inp.name]
                        axisnum = int(inp.id)

                        ini.set_value("[Joy:JS:0]", f"Axis{axisnum}deadzone", "0.25")
                        ini.set_value("[Joy:JS:0]", f"Axis{axisnum}scale", mapping["scale"])
                        ini.set_value("[Joy:JS:0]", f"Axis{axisnum}map", str(mapping["map"]))
            else:
                ini.set_value(f"[Joy:JS:{n}]", "Enabled", "0")

        ini.write()

    def generate(self, system, rom, playersControllers, metadata, guns, wheels, gameResolution):
        rom_path = Path(rom)

        mkdir_if_not_exists(_CONFIG_DIR)
        mkdir_if_not_exists(_SOUND_FONTS_DIR)
        mkdir_if_not_exists(_FM_BANKS_DIR)

        api_config = self._determine_api_config(system)
        self._create_script_file(system, api_config)
        self._update_ini_file(system, rom_path, playersControllers)

        commandArray = ["gzdoom"]

        if rom_path.suffix == ".gzdoom":
            wad_args = shlex.split(rom_path.read_text())
            commandArray.extend(wad_args)
        else:
            commandArray.extend(["-iwad", rom_path.name])

        commandArray.extend([
            "-exec", str(_SCRIPT_FILE),
            "-width", str(gameResolution["width"]),
            "-height", str(gameResolution["height"]),
        ])

        if system.getOptBoolean("nologo"):
            commandArray.append("-nologo")

        sdl_config = generate_sdl_game_controller_config(playersControllers)

        return Command.Command(array=commandArray, env={
            "SDL_GAMECONTROLLERCONFIG": sdl_config,
            "SDL_JOYSTICK_HIDAPI": "0"
        })

    def getInGameRatio(self, config, gameResolution, rom):
        return 16/9
