#!/bin/sh

case "$1" in
  start)
    for f in /usr/lib/python*/site-packages/configgen/emulatorlauncher.py; do
      [ -f "$f" ] || continue
      python3 -m compileall -q "$f" >/dev/null 2>&1
      break
    done
    ;;
esac

exit 0
