#!/bin/sh

BOARD=$(cat /boot/boot/knulli.board)
if [ "$BOARD" != "powkiddy-v90s" ] && [ "$BOARD" != "powkiddy-v20" ] && [ "$BOARD" != "magicx-zero-28" ]; then
    exit 1
fi

case "$1" in
    start)
        if [ "$BOARD" = "magicx-zero-28" ]; then
            amixer -c 0 sset 'Headphone' on
            amixer -c 0 sset 'Headphone' 3
            amixer -c 0 sset 'HpSpeaker' on
            amixer -c 0 sset 'LINEOUT' on 2>/dev/null || true
            amixer -c 0 sset 'DAC volume' 160 160 2>/dev/null || true
            amixer -c 0 sset 'DAC Swap' Off 2>/dev/null || true
        else
            state=`switch-state SW_HEADPHONE_INSERT 2>/dev/null`
            echo Audio jack state: $state
            if [ "$state" = "1" ]; then
                knulli-audio set headphone
            else
                knulli-audio set speakers
            fi
            amixer -D hw:audiocodec sset LINEOUT on
        fi
        ;;
    stop)
        # do nothing
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
