LABEL  knulli.linux
LINUX  /boot/linux
FDTDIR /fdts
APPEND initrd=/boot/initrd.lz4 label=KNULLI rootwait quiet loglevel=0 console=tty3 console=ttyS2,1500000n8 fbcon=rotate:${fbcon_rotate} vt.global_cursor_default=0
